// Code generated by go generate; DO NOT EDIT.
// This file was generated from "pagination/generator/pageables_generator.go" at
// 2020-08-18 22:10:25.016724 -0500 CDT m=+0.001455522
// using types listed in "pagination/generator/pageables.yml"

package pagination

import (
	"github.com/well-informed/wellinformed/graph/model"
)

func InteractionsToNodes(list []*model.Interaction) []*model.Node {
	nodes := make([]*model.Node, len(list))
	for _, item := range list {
		nodes = append(nodes, &model.Node{
			Value: item,
			ID:    item.ID,
		})
	}
	return nodes
}

func ContentItemsToNodes(list []*model.ContentItem) []*model.Node {
	nodes := make([]*model.Node, len(list))
	for _, item := range list {
		nodes = append(nodes, &model.Node{
			Value: item,
			ID:    item.ID,
		})
	}
	return nodes
}

func SrcRSSFeedsToNodes(list []*model.SrcRSSFeed) []*model.Node {
	nodes := make([]*model.Node, len(list))
	for _, item := range list {
		nodes = append(nodes, &model.Node{
			Value: item,
			ID:    item.ID,
		})
	}
	return nodes
}

func UserSubscriptionsToNodes(list []*model.UserSubscription) []*model.Node {
	nodes := make([]*model.Node, len(list))
	for _, item := range list {
		nodes = append(nodes, &model.Node{
			Value: item,
			ID:    item.ID,
		})
	}
	return nodes
}

